# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from replica import metadata_pb2 as replica_dot_metadata__pb2
from replica import replication_pb2 as replica_dot_replication__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in replica/metadata_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MetadataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterNode = channel.unary_unary(
                '/metadata.MetadataService/RegisterNode',
                request_serializer=replica_dot_metadata__pb2.RegisterRequest.SerializeToString,
                response_deserializer=replica_dot_metadata__pb2.ClusterState.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/metadata.MetadataService/Heartbeat',
                request_serializer=replica_dot_metadata__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=replica_dot_metadata__pb2.ClusterState.FromString,
                _registered_method=True)
        self.GetClusterState = channel.unary_unary(
                '/metadata.MetadataService/GetClusterState',
                request_serializer=replica_dot_replication__pb2.Empty.SerializeToString,
                response_deserializer=replica_dot_metadata__pb2.ClusterState.FromString,
                _registered_method=True)
        self.UpdateClusterState = channel.unary_unary(
                '/metadata.MetadataService/UpdateClusterState',
                request_serializer=replica_dot_metadata__pb2.ClusterState.SerializeToString,
                response_deserializer=replica_dot_replication__pb2.Empty.FromString,
                _registered_method=True)
        self.WatchClusterState = channel.unary_stream(
                '/metadata.MetadataService/WatchClusterState',
                request_serializer=replica_dot_replication__pb2.Empty.SerializeToString,
                response_deserializer=replica_dot_metadata__pb2.ClusterState.FromString,
                _registered_method=True)


class MetadataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClusterState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateClusterState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchClusterState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MetadataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=replica_dot_metadata__pb2.RegisterRequest.FromString,
                    response_serializer=replica_dot_metadata__pb2.ClusterState.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=replica_dot_metadata__pb2.HeartbeatRequest.FromString,
                    response_serializer=replica_dot_metadata__pb2.ClusterState.SerializeToString,
            ),
            'GetClusterState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClusterState,
                    request_deserializer=replica_dot_replication__pb2.Empty.FromString,
                    response_serializer=replica_dot_metadata__pb2.ClusterState.SerializeToString,
            ),
            'UpdateClusterState': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateClusterState,
                    request_deserializer=replica_dot_metadata__pb2.ClusterState.FromString,
                    response_serializer=replica_dot_replication__pb2.Empty.SerializeToString,
            ),
            'WatchClusterState': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchClusterState,
                    request_deserializer=replica_dot_replication__pb2.Empty.FromString,
                    response_serializer=replica_dot_metadata__pb2.ClusterState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'metadata.MetadataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('metadata.MetadataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MetadataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metadata.MetadataService/RegisterNode',
            replica_dot_metadata__pb2.RegisterRequest.SerializeToString,
            replica_dot_metadata__pb2.ClusterState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metadata.MetadataService/Heartbeat',
            replica_dot_metadata__pb2.HeartbeatRequest.SerializeToString,
            replica_dot_metadata__pb2.ClusterState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClusterState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metadata.MetadataService/GetClusterState',
            replica_dot_replication__pb2.Empty.SerializeToString,
            replica_dot_metadata__pb2.ClusterState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateClusterState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metadata.MetadataService/UpdateClusterState',
            replica_dot_metadata__pb2.ClusterState.SerializeToString,
            replica_dot_replication__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchClusterState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/metadata.MetadataService/WatchClusterState',
            replica_dot_replication__pb2.Empty.SerializeToString,
            replica_dot_metadata__pb2.ClusterState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
