# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metadata.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'metadata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import replication_pb2 as replication__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emetadata.proto\x12\x08metadata\x1a\x11replication.proto\"7\n\x08NodeInfo\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"3\n\x0fRegisterRequest\x12 \n\x04node\x18\x01 \x01(\x0b\x32\x12.metadata.NodeInfo\"#\n\x10HeartbeatRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"c\n\x0c\x43lusterState\x12!\n\x05nodes\x18\x01 \x03(\x0b\x32\x12.metadata.NodeInfo\x12\x30\n\rpartition_map\x18\x02 \x01(\x0b\x32\x19.replication.PartitionMap2\xd9\x02\n\x0fMetadataService\x12\x41\n\x0cRegisterNode\x12\x19.metadata.RegisterRequest\x1a\x16.metadata.ClusterState\x12?\n\tHeartbeat\x12\x1a.metadata.HeartbeatRequest\x1a\x16.metadata.ClusterState\x12=\n\x0fGetClusterState\x12\x12.replication.Empty\x1a\x16.metadata.ClusterState\x12@\n\x12UpdateClusterState\x12\x16.metadata.ClusterState\x1a\x12.replication.Empty\x12\x41\n\x11WatchClusterState\x12\x12.replication.Empty\x1a\x16.metadata.ClusterState0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NODEINFO']._serialized_start=47
  _globals['_NODEINFO']._serialized_end=102
  _globals['_REGISTERREQUEST']._serialized_start=104
  _globals['_REGISTERREQUEST']._serialized_end=155
  _globals['_HEARTBEATREQUEST']._serialized_start=157
  _globals['_HEARTBEATREQUEST']._serialized_end=192
  _globals['_CLUSTERSTATE']._serialized_start=194
  _globals['_CLUSTERSTATE']._serialized_end=293
  _globals['_METADATASERVICE']._serialized_start=296
  _globals['_METADATASERVICE']._serialized_end=641
# @@protoc_insertion_point(module_scope)
